Repository FANMIX-Works/FANMIX-BE, pull requests merged in 2024-10, with the labels that each got.

#28 ✨ feat:#16 인플루언서 도메인 관련 API GET 제외 구현
  src/main/java/com/fanmix/api/common/aspect/ClientIp.java
  src/main/java/com/fanmix/api/common/aspect/ClientIpAspect.java
  src/main/java/com/fanmix/api/common/conf/SecurityConfig.java
  src/main/java/com/fanmix/api/common/exception/CommonExceptionHandler.java
  src/main/java/com/fanmix/api/common/redis/constants/InfluencerRedisConstants.java
  src/main/java/com/fanmix/api/domain/fan/controller/FanController.java
  src/main/java/com/fanmix/api/domain/fan/entity/Fan.java
  src/main/java/com/fanmix/api/domain/fan/entity/FanStatus.java
  src/main/java/com/fanmix/api/domain/fan/repository/FanRepository.java
  src/main/java/com/fanmix/api/domain/fan/service/FanService.java
  src/main/java/com/fanmix/api/domain/influencer/controller/InfluencerController.java
  src/main/java/com/fanmix/api/domain/influencer/dto/response/InfluencerResponseDto.java
  src/main/java/com/fanmix/api/domain/influencer/entity/Influencer.java
  src/main/java/com/fanmix/api/domain/influencer/entity/PlatformType.java
  src/main/java/com/fanmix/api/domain/influencer/entity/SocialMedia.java
  src/main/java/com/fanmix/api/domain/influencer/exception/InfluencerErrorCode.java
  src/main/java/com/fanmix/api/domain/influencer/exception/InfluencerException.java
  src/main/java/com/fanmix/api/domain/influencer/repository/InfluencerRepository.java
  src/main/java/com/fanmix/api/domain/influencer/repository/tag/InfluencerTagMapperRepository.java
  src/main/java/com/fanmix/api/domain/influencer/service/InfluencerService.java
  src/main/java/com/fanmix/api/domain/review/controller/ReviewController.java
  src/main/java/com/fanmix/api/domain/review/dto/request/ReviewCommentRequestDto.java
  src/main/java/com/fanmix/api/domain/review/dto/request/ReviewLikeOrDislikeRequestDto.java
  src/main/java/com/fanmix/api/domain/review/dto/request/ReviewRequestDto.java
  src/main/java/com/fanmix/api/domain/review/entity/Review.java
  src/main/java/com/fanmix/api/domain/review/entity/ReviewComment.java
  src/main/java/com/fanmix/api/domain/review/entity/ReviewLikeDislike.java
  src/main/java/com/fanmix/api/domain/review/exception/ReviewErrorCode.java
  src/main/java/com/fanmix/api/domain/review/exception/ReviewException.java
  src/main/java/com/fanmix/api/domain/review/repository/ReviewCommentRepository.java
  src/main/java/com/fanmix/api/domain/review/repository/ReviewLikeDislikeRepository.java
  src/main/java/com/fanmix/api/domain/review/repository/ReviewRepository.java
  src/main/java/com/fanmix/api/domain/review/service/ReviewService.java
Labels: ✨ feat

#29 배포 위한 Develop -> Main PR
  .gitignore
  build.gradle
  src/main/java/com/fanmix/api/common/aspect/ClientIp.java
  src/main/java/com/fanmix/api/common/aspect/ClientIpAspect.java
  src/main/java/com/fanmix/api/common/conf/QuerydslConfig.java
  src/main/java/com/fanmix/api/common/conf/SecurityConfig.java
  src/main/java/com/fanmix/api/common/exception/CommonExceptionHandler.java
  src/main/java/com/fanmix/api/common/redis/RedisConfig.java
  src/main/java/com/fanmix/api/common/redis/RedisService.java
  src/main/java/com/fanmix/api/common/redis/constants/InfluencerRedisConstants.java
  src/main/java/com/fanmix/api/domain/fan/controller/FanController.java
  src/main/java/com/fanmix/api/domain/fan/entity/Fan.java
  src/main/java/com/fanmix/api/domain/fan/entity/FanStatus.java
  src/main/java/com/fanmix/api/domain/fan/repository/FanRepository.java
  src/main/java/com/fanmix/api/domain/fan/service/FanService.java
  src/main/java/com/fanmix/api/domain/influencer/controller/InfluencerController.java
  src/main/java/com/fanmix/api/domain/influencer/dto/response/InfluencerResponseDto.java
  src/main/java/com/fanmix/api/domain/influencer/entity/Influencer.java
  src/main/java/com/fanmix/api/domain/influencer/entity/PlatformType.java
  src/main/java/com/fanmix/api/domain/influencer/entity/SocialMedia.java
  src/main/java/com/fanmix/api/domain/influencer/exception/InfluencerErrorCode.java
  src/main/java/com/fanmix/api/domain/influencer/exception/InfluencerException.java
  src/main/java/com/fanmix/api/domain/influencer/repository/InfluencerRepository.java
  src/main/java/com/fanmix/api/domain/influencer/repository/tag/InfluencerTagMapperRepository.java
  src/main/java/com/fanmix/api/domain/influencer/service/InfluencerService.java
  src/main/java/com/fanmix/api/domain/review/controller/ReviewController.java
  src/main/java/com/fanmix/api/domain/review/dto/request/ReviewCommentRequestDto.java
  src/main/java/com/fanmix/api/domain/review/dto/request/ReviewLikeOrDislikeRequestDto.java
  src/main/java/com/fanmix/api/domain/review/dto/request/ReviewRequestDto.java
  src/main/java/com/fanmix/api/domain/review/entity/Review.java
  src/main/java/com/fanmix/api/domain/review/entity/ReviewComment.java
  src/main/java/com/fanmix/api/domain/review/entity/ReviewLikeDislike.java
  src/main/java/com/fanmix/api/domain/review/exception/ReviewErrorCode.java
  src/main/java/com/fanmix/api/domain/review/exception/ReviewException.java
  src/main/java/com/fanmix/api/domain/review/repository/ReviewCommentRepository.java
  src/main/java/com/fanmix/api/domain/review/repository/ReviewLikeDislikeRepository.java
  src/main/java/com/fanmix/api/domain/review/repository/ReviewRepository.java
  src/main/java/com/fanmix/api/domain/review/service/ReviewService.java
Labels: ✨ feat

#31 ✨ feat:#16 인플루언서 검색, 한줄리뷰 전체 보기 api 구현
  src/main/java/com/fanmix/api/FanmixApplication.java
  src/main/java/com/fanmix/api/domain/influencer/controller/InfluencerController.java
  src/main/java/com/fanmix/api/domain/influencer/dto/enums/SearchType.java
  src/main/java/com/fanmix/api/domain/influencer/dto/enums/Sort.java
  src/main/java/com/fanmix/api/domain/influencer/dto/response/InfluencerResponseDto.java
  src/main/java/com/fanmix/api/domain/influencer/entity/Influencer.java
  src/main/java/com/fanmix/api/domain/influencer/entity/InfluencerRatingCache.java
  src/main/java/com/fanmix/api/domain/influencer/exception/InfluencerErrorCode.java
  src/main/java/com/fanmix/api/domain/influencer/repository/InfluencerRepository.java
  src/main/java/com/fanmix/api/domain/influencer/repository/cache/InfluencerCacheQuerydslRepository.java
  src/main/java/com/fanmix/api/domain/influencer/repository/cache/InfluencerCacheQuerydslRepositoryImpl.java
  src/main/java/com/fanmix/api/domain/influencer/repository/cache/InfluencerRatingCacheRepository.java
  src/main/java/com/fanmix/api/domain/influencer/service/InfluencerScheduledService.java
  src/main/java/com/fanmix/api/domain/influencer/service/InfluencerService.java
  src/main/java/com/fanmix/api/domain/review/controller/ReviewController.java
  src/main/java/com/fanmix/api/domain/review/dto/enums/Sort.java
  src/main/java/com/fanmix/api/domain/review/dto/response/ReviewResponseDto.java
  src/main/java/com/fanmix/api/domain/review/entity/ReviewLikeDislike.java
  src/main/java/com/fanmix/api/domain/review/repository/ReviewLikeDislikeRepository.java
  src/main/java/com/fanmix/api/domain/review/repository/ReviewQuerydslRepository.java
  src/main/java/com/fanmix/api/domain/review/repository/ReviewQuerydslRepositoryImpl.java
  src/main/java/com/fanmix/api/domain/review/repository/ReviewRepository.java
  src/main/java/com/fanmix/api/domain/review/service/ReviewService.java
Labels: ✨ feat

#32 배포 위한 Develop -> Main PR
  src/main/java/com/fanmix/api/FanmixApplication.java
  src/main/java/com/fanmix/api/domain/influencer/controller/InfluencerController.java
  src/main/java/com/fanmix/api/domain/influencer/dto/enums/SearchType.java
  src/main/java/com/fanmix/api/domain/influencer/dto/enums/Sort.java
  src/main/java/com/fanmix/api/domain/influencer/dto/response/InfluencerResponseDto.java
  src/main/java/com/fanmix/api/domain/influencer/entity/Influencer.java
  src/main/java/com/fanmix/api/domain/influencer/entity/InfluencerRatingCache.java
  src/main/java/com/fanmix/api/domain/influencer/exception/InfluencerErrorCode.java
  src/main/java/com/fanmix/api/domain/influencer/repository/InfluencerRepository.java
  src/main/java/com/fanmix/api/domain/influencer/repository/cache/InfluencerCacheQuerydslRepository.java
  src/main/java/com/fanmix/api/domain/influencer/repository/cache/InfluencerCacheQuerydslRepositoryImpl.java
  src/main/java/com/fanmix/api/domain/influencer/repository/cache/InfluencerRatingCacheRepository.java
  src/main/java/com/fanmix/api/domain/influencer/service/InfluencerScheduledService.java
  src/main/java/com/fanmix/api/domain/influencer/service/InfluencerService.java
  src/main/java/com/fanmix/api/domain/review/controller/ReviewController.java
  src/main/java/com/fanmix/api/domain/review/dto/enums/Sort.java
  src/main/java/com/fanmix/api/domain/review/dto/response/ReviewResponseDto.java
  src/main/java/com/fanmix/api/domain/review/entity/ReviewLikeDislike.java
  src/main/java/com/fanmix/api/domain/review/repository/ReviewLikeDislikeRepository.java
  src/main/java/com/fanmix/api/domain/review/repository/ReviewQuerydslRepository.java
  src/main/java/com/fanmix/api/domain/review/repository/ReviewQuerydslRepositoryImpl.java
  src/main/java/com/fanmix/api/domain/review/repository/ReviewRepository.java
  src/main/java/com/fanmix/api/domain/review/service/ReviewService.java
Labels: ✨ feat

#34 Entity Erd 에 맞춰 리팩토링
  src/main/java/com/fanmix/api/domain/fan/entity/Fan.java
  src/main/java/com/fanmix/api/domain/influencer/controller/InfluencerController.java
  src/main/java/com/fanmix/api/domain/influencer/entity/Influencer.java
  src/main/java/com/fanmix/api/domain/influencer/entity/InfluencerRatingCache.java
  src/main/java/com/fanmix/api/domain/influencer/entity/SocialMedia.java
  src/main/java/com/fanmix/api/domain/influencer/entity/tag/InfluencerTag.java
  src/main/java/com/fanmix/api/domain/review/entity/Review.java
  src/main/java/com/fanmix/api/domain/review/entity/ReviewComment.java
  src/main/java/com/fanmix/api/domain/review/entity/ReviewLikeDislike.java
  src/main/java/com/fanmix/api/domain/review/repository/ReviewRepository.java
Labels: ♻️ refactor

#40 ✨ feat:#16 리뷰 관련 모든 api 구현
  src/main/java/com/fanmix/api/common/conf/SecurityConfig.java
  src/main/java/com/fanmix/api/domain/member/controller/MemberController.java
  src/main/java/com/fanmix/api/domain/member/dto/LatestReviewResponseDto.java
  src/main/java/com/fanmix/api/domain/member/service/MemberService.java
  src/main/java/com/fanmix/api/domain/review/controller/ReviewController.java
  src/main/java/com/fanmix/api/domain/review/dto/response/ReviewResponseDto.java
  src/main/java/com/fanmix/api/domain/review/entity/Review.java
  src/main/java/com/fanmix/api/domain/review/repository/ReviewQuerydslRepository.java
  src/main/java/com/fanmix/api/domain/review/repository/ReviewQuerydslRepositoryImpl.java
  src/main/java/com/fanmix/api/domain/review/repository/ReviewRepository.java
  src/main/java/com/fanmix/api/domain/review/service/ReviewService.java
Labels: ✨ feat

#42 배포 위한 Develop -> Main PR
  src/main/java/com/fanmix/api/common/conf/SecurityConfig.java
  src/main/java/com/fanmix/api/common/redis/constants/InfluencerRedisConstants.java
  src/main/java/com/fanmix/api/domain/influencer/controller/InfluencerController.java
  src/main/java/com/fanmix/api/domain/influencer/dto/response/InfluencerResponseDto.java
  src/main/java/com/fanmix/api/domain/influencer/entity/Influencer.java
  src/main/java/com/fanmix/api/domain/influencer/repository/InfluencerRepository.java
  src/main/java/com/fanmix/api/domain/influencer/service/InfluencerScheduledService.java
  src/main/java/com/fanmix/api/domain/influencer/service/InfluencerService.java
  src/main/java/com/fanmix/api/domain/member/controller/MemberController.java
  src/main/java/com/fanmix/api/domain/member/dto/LatestReviewResponseDto.java
  src/main/java/com/fanmix/api/domain/member/service/MemberService.java
  src/main/java/com/fanmix/api/domain/review/controller/ReviewController.java
  src/main/java/com/fanmix/api/domain/review/dto/response/ReviewResponseDto.java
  src/main/java/com/fanmix/api/domain/review/entity/Review.java
  src/main/java/com/fanmix/api/domain/review/repository/ReviewQuerydslRepository.java
  src/main/java/com/fanmix/api/domain/review/repository/ReviewQuerydslRepositoryImpl.java
  src/main/java/com/fanmix/api/domain/review/repository/ReviewRepository.java
  src/main/java/com/fanmix/api/domain/review/service/ReviewService.java
Labels: ✨ feat

#44 ✨ feat: Feat/community -> Develop PR
  src/main/java/com/fanmix/api/domain/comment/controller/CommentController.java
  src/main/java/com/fanmix/api/domain/comment/controller/FanChannelCommentController.java
  src/main/java/com/fanmix/api/domain/comment/dto/AddCommentRequest.java
  src/main/java/com/fanmix/api/domain/comment/dto/CommentResponse.java
  src/main/java/com/fanmix/api/domain/comment/dto/UpdateCommentRequest.java
  src/main/java/com/fanmix/api/domain/comment/entity/Comment.java
  src/main/java/com/fanmix/api/domain/comment/service/CommentService.java
  src/main/java/com/fanmix/api/domain/comment/service/FanChannelCommentService.java
  src/main/java/com/fanmix/api/domain/community/controller/CommunityController.java
  src/main/java/com/fanmix/api/domain/community/controller/FanChannelController.java
  src/main/java/com/fanmix/api/domain/community/dto/AddCommunityRequest.java
  src/main/java/com/fanmix/api/domain/community/dto/AddFanChannelRequest.java
  src/main/java/com/fanmix/api/domain/community/dto/CommunityResponse.java
  src/main/java/com/fanmix/api/domain/community/dto/FanChannelResponse.java
  src/main/java/com/fanmix/api/domain/community/dto/FollowCommunityResponse.java
  src/main/java/com/fanmix/api/domain/community/entity/Community.java
  src/main/java/com/fanmix/api/domain/community/entity/CommunityFollow.java
  src/main/java/com/fanmix/api/domain/community/exception/CommunityErrorCode.java
  src/main/java/com/fanmix/api/domain/community/repository/CommunityFollowRepository.java
  src/main/java/com/fanmix/api/domain/community/repository/CommunityRepository.java
  src/main/java/com/fanmix/api/domain/community/service/CommunityService.java
  src/main/java/com/fanmix/api/domain/community/service/FanChannelService.java
  src/main/java/com/fanmix/api/domain/fan/repository/FanRepository.java
  src/main/java/com/fanmix/api/domain/member/entity/Member.java
  src/main/java/com/fanmix/api/domain/post/controller/FanChannelPostController.java
  src/main/java/com/fanmix/api/domain/post/controller/PostController.java
  src/main/java/com/fanmix/api/domain/post/dto/PopularPostsResponse.java
  src/main/java/com/fanmix/api/domain/post/dto/PostListResponse.java
  src/main/java/com/fanmix/api/domain/post/dto/PostResponse.java
  src/main/java/com/fanmix/api/domain/post/dto/Top5PostResponse.java
  src/main/java/com/fanmix/api/domain/post/repository/PostRepository.java
  src/main/java/com/fanmix/api/domain/post/service/FanChannelPostService.java
  src/main/java/com/fanmix/api/domain/post/service/PostService.java
Labels: ✨ feat

#45 Feat/community -> Main PR
  src/main/java/com/fanmix/api/domain/comment/controller/CommentController.java
  src/main/java/com/fanmix/api/domain/comment/controller/FanChannelCommentController.java
  src/main/java/com/fanmix/api/domain/comment/dto/AddCommentRequest.java
  src/main/java/com/fanmix/api/domain/comment/dto/CommentResponse.java
  src/main/java/com/fanmix/api/domain/comment/dto/UpdateCommentRequest.java
  src/main/java/com/fanmix/api/domain/comment/entity/Comment.java
  src/main/java/com/fanmix/api/domain/comment/service/CommentService.java
  src/main/java/com/fanmix/api/domain/comment/service/FanChannelCommentService.java
  src/main/java/com/fanmix/api/domain/community/controller/CommunityController.java
  src/main/java/com/fanmix/api/domain/community/controller/FanChannelController.java
  src/main/java/com/fanmix/api/domain/community/dto/AddCommunityRequest.java
  src/main/java/com/fanmix/api/domain/community/dto/AddFanChannelRequest.java
  src/main/java/com/fanmix/api/domain/community/dto/CommunityResponse.java
  src/main/java/com/fanmix/api/domain/community/dto/FanChannelResponse.java
  src/main/java/com/fanmix/api/domain/community/dto/FollowCommunityResponse.java
  src/main/java/com/fanmix/api/domain/community/entity/Community.java
  src/main/java/com/fanmix/api/domain/community/entity/CommunityFollow.java
  src/main/java/com/fanmix/api/domain/community/exception/CommunityErrorCode.java
  src/main/java/com/fanmix/api/domain/community/repository/CommunityFollowRepository.java
  src/main/java/com/fanmix/api/domain/community/repository/CommunityRepository.java
  src/main/java/com/fanmix/api/domain/community/service/CommunityService.java
  src/main/java/com/fanmix/api/domain/community/service/FanChannelService.java
  src/main/java/com/fanmix/api/domain/fan/repository/FanRepository.java
  src/main/java/com/fanmix/api/domain/member/dto/MyFollowResponseDto.java
  src/main/java/com/fanmix/api/domain/member/entity/Member.java
  src/main/java/com/fanmix/api/domain/member/service/MemberService.java
  src/main/java/com/fanmix/api/domain/post/controller/FanChannelPostController.java
  src/main/java/com/fanmix/api/domain/post/controller/PostController.java
  src/main/java/com/fanmix/api/domain/post/dto/PopularPostsResponse.java
  src/main/java/com/fanmix/api/domain/post/dto/PostListResponse.java
  src/main/java/com/fanmix/api/domain/post/dto/PostResponse.java
  src/main/java/com/fanmix/api/domain/post/dto/Top5PostResponse.java
  src/main/java/com/fanmix/api/domain/post/repository/PostRepository.java
  src/main/java/com/fanmix/api/domain/post/service/FanChannelPostService.java
  src/main/java/com/fanmix/api/domain/post/service/PostService.java
Labels: ✨ feat

#46 ♻️ refactor:#16 api 에서 추가된 정보 추가
  src/main/java/com/fanmix/api/domain/community/repository/CommunityRepository.java
  src/main/java/com/fanmix/api/domain/influencer/dto/response/InfluencerResponseDto.java
  src/main/java/com/fanmix/api/domain/influencer/service/InfluencerService.java
Labels: ♻️ refactor

#49 ♻️ refactor:#48 에서 Review 도메인 task 완료
  src/main/java/com/fanmix/api/domain/review/controller/ReviewController.java
  src/main/java/com/fanmix/api/domain/review/dto/response/ReviewResponseDto.java
  src/main/java/com/fanmix/api/domain/review/service/ReviewService.java
Labels: ♻️ refactor

#50 ♻️ refactor: 커뮤니티, 팬채널 관련 등록/수정 api Reponse 수정
  src/main/java/com/fanmix/api/domain/comment/controller/CommentController.java
  src/main/java/com/fanmix/api/domain/comment/controller/FanChannelCommentController.java
  src/main/java/com/fanmix/api/domain/comment/dto/AddCommentRequest.java
  src/main/java/com/fanmix/api/domain/comment/dto/CommentResponse.java
  src/main/java/com/fanmix/api/domain/comment/entity/Comment.java
  src/main/java/com/fanmix/api/domain/comment/service/CommentService.java
  src/main/java/com/fanmix/api/domain/comment/service/FanChannelCommentService.java
  src/main/java/com/fanmix/api/domain/community/controller/CommunityController.java
  src/main/java/com/fanmix/api/domain/community/controller/FanChannelController.java
  src/main/java/com/fanmix/api/domain/community/dto/CommunityResponse.java
  src/main/java/com/fanmix/api/domain/community/service/CommunityService.java
  src/main/java/com/fanmix/api/domain/community/service/FanChannelService.java
  src/main/java/com/fanmix/api/domain/post/controller/FanChannelPostController.java
  src/main/java/com/fanmix/api/domain/post/controller/PostController.java
  src/main/java/com/fanmix/api/domain/post/dto/FanChannelPostResponse.java
  src/main/java/com/fanmix/api/domain/post/dto/PostListResponse.java
  src/main/java/com/fanmix/api/domain/post/dto/PostResponse.java
  src/main/java/com/fanmix/api/domain/post/service/FanChannelPostService.java
  src/main/java/com/fanmix/api/domain/post/service/PostService.java
Labels: ♻️ refactor

#51 ♻️ refactor: #48에서 Community, Post, Comment 도메인 task 완료
  src/main/java/com/fanmix/api/domain/comment/controller/CommentController.java
  src/main/java/com/fanmix/api/domain/comment/controller/FanChannelCommentController.java
  src/main/java/com/fanmix/api/domain/comment/dto/AddCommentRequest.java
  src/main/java/com/fanmix/api/domain/comment/dto/CommentResponse.java
  src/main/java/com/fanmix/api/domain/comment/entity/Comment.java
  src/main/java/com/fanmix/api/domain/comment/service/CommentService.java
  src/main/java/com/fanmix/api/domain/comment/service/FanChannelCommentService.java
  src/main/java/com/fanmix/api/domain/community/controller/CommunityController.java
  src/main/java/com/fanmix/api/domain/community/controller/FanChannelController.java
  src/main/java/com/fanmix/api/domain/community/dto/CommunityResponse.java
  src/main/java/com/fanmix/api/domain/community/service/CommunityService.java
  src/main/java/com/fanmix/api/domain/community/service/FanChannelService.java
  src/main/java/com/fanmix/api/domain/post/controller/FanChannelPostController.java
  src/main/java/com/fanmix/api/domain/post/controller/PostController.java
  src/main/java/com/fanmix/api/domain/post/dto/FanChannelPostResponse.java
  src/main/java/com/fanmix/api/domain/post/dto/PostListResponse.java
  src/main/java/com/fanmix/api/domain/post/dto/PostResponse.java
  src/main/java/com/fanmix/api/domain/post/service/FanChannelPostService.java
  src/main/java/com/fanmix/api/domain/post/service/PostService.java
Labels: ♻️ refactor

#52 🚑 !HOTFIX: group by 없이 집계함수를 사용하는 부분 수정
  src/main/java/com/fanmix/api/domain/review/repository/ReviewQuerydslRepositoryImpl.java
Labels: 🚑 !HOTFIX

#54 🚑 !HOTFIX: 리뷰 좋아요 눌렀는지 판독할 때 실수 수정
  src/main/java/com/fanmix/api/domain/review/repository/ReviewLikeDislikeRepository.java
  src/main/java/com/fanmix/api/domain/review/service/ReviewService.java
Labels: 🚑 !HOTFIX

#56 ♻️ refactor: 인기글 Top5 조회시 Response 형식 수정
  src/main/java/com/fanmix/api/domain/post/dto/PopularPostsResponse.java
  src/main/java/com/fanmix/api/domain/post/dto/PostListResponse.java
Labels: ♻️ refactor

#61 :recycle: refactor: 인증된 인플루언서만 팬채널로써 조회 가능하도록 수정, 비로그인 상태일 때는 팔로잉 여부 false로 변경
  src/main/java/com/fanmix/api/domain/community/controller/FanChannelController.java
  src/main/java/com/fanmix/api/domain/community/dto/FanChannelResponse.java
  src/main/java/com/fanmix/api/domain/community/service/FanChannelService.java
Labels: ♻️ refactor

#62 ♻️ refactor: #61 관련해서 로직 수정, response 수정
  src/main/java/com/fanmix/api/domain/community/controller/FanChannelController.java
  src/main/java/com/fanmix/api/domain/community/dto/FanChannelResponse.java
  src/main/java/com/fanmix/api/domain/community/service/FanChannelService.java
Labels: ♻️ refactor

#67 :sparkles: feat: 커뮤니티에 오늘 안에 새 글이 올라왔는지 여부
  src/main/java/com/fanmix/api/domain/community/controller/CommunityController.java
  src/main/java/com/fanmix/api/domain/community/dto/CommunityNewPostResponse.java
  src/main/java/com/fanmix/api/domain/community/service/CommunityService.java
Labels: ✨ feat

#68 ✨ Develop -> Main Merge PR
  src/main/java/com/fanmix/api/domain/community/controller/CommunityController.java
  src/main/java/com/fanmix/api/domain/community/dto/CommunityNewPostResponse.java
  src/main/java/com/fanmix/api/domain/community/service/CommunityService.java
Labels: ✨ feat

#70 ✨ feat: 커뮤니티, 팬채널 글, 댓글 목록 / 글 상세 조회시 내가 작성한 글/댓글인지 여부 넘기기
  src/main/java/com/fanmix/api/domain/comment/controller/CommentController.java
  src/main/java/com/fanmix/api/domain/comment/controller/FanChannelCommentController.java
  src/main/java/com/fanmix/api/domain/comment/dto/CommentDetailResponse.java
  src/main/java/com/fanmix/api/domain/comment/service/CommentService.java
  src/main/java/com/fanmix/api/domain/comment/service/FanChannelCommentService.java
  src/main/java/com/fanmix/api/domain/post/controller/FanChannelPostController.java
  src/main/java/com/fanmix/api/domain/post/controller/PostController.java
  src/main/java/com/fanmix/api/domain/post/dto/PostDetailResponse.java
  src/main/java/com/fanmix/api/domain/post/dto/PostListResponse.java
  src/main/java/com/fanmix/api/domain/post/repository/PostRepository.java
  src/main/java/com/fanmix/api/domain/post/service/FanChannelPostService.java
  src/main/java/com/fanmix/api/domain/post/service/PostService.java
Labels: ✨ feat

#71 Develop -> Main Merge PR
  src/main/java/com/fanmix/api/domain/comment/controller/CommentController.java
  src/main/java/com/fanmix/api/domain/comment/controller/FanChannelCommentController.java
  src/main/java/com/fanmix/api/domain/comment/dto/CommentDetailResponse.java
  src/main/java/com/fanmix/api/domain/comment/service/CommentService.java
  src/main/java/com/fanmix/api/domain/comment/service/FanChannelCommentService.java
  src/main/java/com/fanmix/api/domain/post/controller/FanChannelPostController.java
  src/main/java/com/fanmix/api/domain/post/controller/PostController.java
  src/main/java/com/fanmix/api/domain/post/dto/PostDetailResponse.java
  src/main/java/com/fanmix/api/domain/post/dto/PostListResponse.java
  src/main/java/com/fanmix/api/domain/post/repository/PostRepository.java
  src/main/java/com/fanmix/api/domain/post/service/FanChannelPostService.java
  src/main/java/com/fanmix/api/domain/post/service/PostService.java
Labels: ✨ feat

#72 :bug: fix: 팬채널 댓글 목록 조회시 멤버 권한 조건 수정
  src/main/java/com/fanmix/api/domain/comment/service/FanChannelCommentService.java
Labels: 🐛 fix

#75 🐛 fix: 팬채널 정보/글/댓글 관련 권한 처리 로직 팬일 경우만 작업 가능하도록 수정
  src/main/java/com/fanmix/api/domain/comment/service/FanChannelCommentService.java
  src/main/java/com/fanmix/api/domain/community/service/FanChannelService.java
  src/main/java/com/fanmix/api/domain/post/dto/PostListResponse.java
  src/main/java/com/fanmix/api/domain/post/service/FanChannelPostService.java
  src/main/java/com/fanmix/api/domain/post/service/PostService.java
Labels: 🐛 fix

#76 Develop -> Main Merge PR
  src/main/java/com/fanmix/api/domain/comment/service/FanChannelCommentService.java
  src/main/java/com/fanmix/api/domain/community/service/FanChannelService.java
  src/main/java/com/fanmix/api/domain/post/dto/PostListResponse.java
  src/main/java/com/fanmix/api/domain/post/service/FanChannelPostService.java
  src/main/java/com/fanmix/api/domain/post/service/PostService.java
Labels: 🐛 fix, ✨ feat

#77 🐛 fix: 커뮤니티, 팬채널 삭제된 게시물 제외 빠진 부분 추가
  src/main/java/com/fanmix/api/domain/comment/dto/CommentDetailResponse.java
  src/main/java/com/fanmix/api/domain/comment/dto/CommentResponse.java
  src/main/java/com/fanmix/api/domain/post/service/FanChannelPostService.java
  src/main/java/com/fanmix/api/domain/post/service/PostService.java
Labels: 🐛 fix

#78 Develop -> Main Merge PR
  src/main/java/com/fanmix/api/domain/comment/dto/CommentDetailResponse.java
  src/main/java/com/fanmix/api/domain/comment/dto/CommentResponse.java
  src/main/java/com/fanmix/api/domain/post/service/FanChannelPostService.java
  src/main/java/com/fanmix/api/domain/post/service/PostService.java
Labels: 🐛 fix, ✨ feat

#79 ✨ feat: 커뮤니티, 팬채널 글 상세 조회시 내가 추천/비추천 했는지 여부
  src/main/java/com/fanmix/api/domain/post/dto/PostDetailResponse.java
  src/main/java/com/fanmix/api/domain/post/repository/PostLikeDisLikeRepository.java
  src/main/java/com/fanmix/api/domain/post/service/FanChannelPostService.java
  src/main/java/com/fanmix/api/domain/post/service/PostService.java
Labels: ✨ feat

#80 Develop -> Main Merge PR
  src/main/java/com/fanmix/api/domain/post/dto/PostDetailResponse.java
  src/main/java/com/fanmix/api/domain/post/repository/PostLikeDisLikeRepository.java
  src/main/java/com/fanmix/api/domain/post/service/FanChannelPostService.java
  src/main/java/com/fanmix/api/domain/post/service/PostService.java
Labels: ✨ feat

#81 :sparkles: feat: 커뮤니티, 팬채널 글 상세/목록 조회 Response 형식에 memberId 추가
  src/main/java/com/fanmix/api/domain/post/dto/FanChannelPostResponse.java
  src/main/java/com/fanmix/api/domain/post/dto/PostDetailResponse.java
  src/main/java/com/fanmix/api/domain/post/dto/PostListResponse.java
  src/main/java/com/fanmix/api/domain/post/dto/PostResponse.java
Labels: ✨ feat

#82 Develop -> Main Merge PR
  src/main/java/com/fanmix/api/domain/post/dto/FanChannelPostResponse.java
  src/main/java/com/fanmix/api/domain/post/dto/PostDetailResponse.java
  src/main/java/com/fanmix/api/domain/post/dto/PostListResponse.java
  src/main/java/com/fanmix/api/domain/post/dto/PostResponse.java
Labels: ✨ feat
